openapi: 3.0.0
info:
  title: gallery-api
  version: 1.0.0
servers:
  - url: https://gallery-api-kwa8.onrender.com
  - name: pictures
paths:
  /api/v1/pictures:
    get:
      tags:
        - pictures
      summary: Get All Pictures
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
