openapi: 3.0.0
info:
  title: back-networker-delta
  version: 1.0.0
servers:
  - url: https://back-networker-delta.onrender.com
tags:
  - name: auth
  - name: wake up
  - name: users
paths:
  /api/v1/auth/register:
    post:
      tags:
        - auth
      summary: Register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                firstName: Biba
                lastName: Boba
                nickName: biba_0321
                address: Guga str. Lviv, Ukraine
                postCode: 79-021
                phone: '+380930362479'
                linkedIn: https://www.linkedin.com/in/b-ty/
                company: Boba.inc
                email: biba_boba@gmail.com
                password: boba123
      responses:
        '201':
          description: Successful response
          content:
            application/json: {}
  /api/v1/auth/login:
    post:
      tags:
        - auth
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: biba_boba@gmail.com
                password: boba123
      responses:
        '202':
          description: Successful response
          content:
            application/json: {}
  /api/v1/auth/logout:
    delete:
      tags:
        - auth
      summary: Logout
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/wake-up:
    get:
      tags:
        - wake up
      summary: Wake Up
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/users:
    get:
      tags:
        - users
      summary: Get All Users
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v1/users/:id:
    get:
      tags:
        - users
      summary: Get User By Id
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
