openapi: 3.0.0
info:
  title: back-end_pet
  version: 1.0.0
servers:
  - url: https://back-end-pet.onrender.com
tags:
  - name: auth
paths:
  /api/v1/auth/register:
    post:
      tags:
        - auth
      summary: Register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Lida
                email: lida_petrivna67@gmail.com
                password: lida123
      responses:
        '201':
          description: Successful response
          content:
            application/json: {}
  /api/v1/auth/login:
    post:
      tags:
        - auth
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: lida_petrivna67@gmail.com
                password: lida123
      responses:
        '202':
          description: Successful response
          content:
            application/json: {}
